import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <Image alt='logo' src="/image/related2.jpg" className='m-0 p-0 w-80' height={35}  width={160} / >
      </main>
    </div>
  )
}
